export const FONT_SIZE = {
  // 타이틀, 로고용
  TITLE_48: 48,
  TITLE_32: 32,
  TITLE_24: 24,

  // 일반 폰트용
  LARGE: 20,
  MEDIUM: 16,
  SMALL: 12,
};

// VERTICAL: 정중앙

export const COMMON_SIZE = {
  BORDER_RADIUS: 5, // 전체 박스의 모서리 둥글기

  LINE_WIDTH: 1, // 관심분야 리스트에 쓰는 구분선

  PROFILE_BOX_PADDING_HORIZONTAL: 40,
  PROFILE_BOX_PADDING_VERTICAL: 20,
  CODE_BOX_PADDING: 20,
  PROFILE_BOX_DT_MARGIN_BOTTOM: 10,
  PROFILE_BOX_DD_MARGIN_BOTTOM: 20,

  EDITOR_BOX_INPUT_BORDER_RADIUS: 5,
  EDITOR_BOX_INPUT_HEIGHT: 20,

  SCROLLBAR_WIDTH: 10, // 메인화면 프로필 리스트 스크롤바

  PROFILELIST_SINGLE_WIDTH: 720,
  PROFILELIST_TRIPLE_WIDTH: 1080,
};

export const LOGIN_SIZE = {
  // Register Page
  INPUT_PADDING_HORIZONTAL: 10,
  INPUT_PADDING_VERTICAL: 5,
  INPUT_BORDER_RADIUS: 5,
  INPUT_MARGIN_BOTTOM: 30,
};

export const LOGO_SIZE = {
  MAIN_LOGO_WIDTH: '133.88',
  MAIN_LOGO_HEIGHT: '30',
  LOGIN_LOGO_WIDTH: '160',
  LOGIN_LOGO_HEIGHT: '35.86',
};
