name: development CI

on:
  push:
    branches:
      - "**/be-**"
  pull_request:
    branches:
      - "**/be-**"

defaults:
  run:
    working-directory: ./server

jobs:
  node_CI:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Check prettier, eslint & Test
        run: npm ci
